/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Auth/login/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetAllPublicBundlesResponse"];
                        "application/json": components["schemas"]["GetAllPublicBundlesResponse"];
                        "text/json": components["schemas"]["GetAllPublicBundlesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Bundle/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetSingleBundleResponse"];
                        "application/json": components["schemas"]["GetSingleBundleResponse"];
                        "text/json": components["schemas"]["GetSingleBundleResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetAllPublicTemplatesResponse"];
                        "application/json": components["schemas"]["GetAllPublicTemplatesResponse"];
                        "text/json": components["schemas"]["GetAllPublicTemplatesResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostTemplateRequest"];
                    "text/json": components["schemas"]["PostTemplateRequest"];
                    "application/*+json": components["schemas"]["PostTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PostTemplateResponse"];
                        "application/json": components["schemas"]["PostTemplateResponse"];
                        "text/json": components["schemas"]["PostTemplateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Template/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetSingleTemplateResponse"];
                        "application/json": components["schemas"]["GetSingleTemplateResponse"];
                        "text/json": components["schemas"]["GetSingleTemplateResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Template/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GetUploadUrlRequest"];
                    "text/json": components["schemas"]["GetUploadUrlRequest"];
                    "application/*+json": components["schemas"]["GetUploadUrlRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUploadUrlResponse"];
                        "application/json": components["schemas"]["GetUploadUrlResponse"];
                        "text/json": components["schemas"]["GetUploadUrlResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostCommentRequest"];
                    "text/json": components["schemas"]["PostCommentRequest"];
                    "application/*+json": components["schemas"]["PostCommentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/User/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUserInfoResponse"];
                        "application/json": components["schemas"]["GetUserInfoResponse"];
                        "text/json": components["schemas"]["GetUserInfoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/User/userProfile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUserInfoResponse"];
                        "application/json": components["schemas"]["GetUserInfoResponse"];
                        "text/json": components["schemas"]["GetUserInfoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthorDto: {
            /** Format: uuid */
            id?: string;
            email?: string;
            displayName?: string;
        };
        BundleDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string | null;
            /** Format: double */
            price?: number;
            currency?: components["schemas"]["Currency"];
            visibility?: components["schemas"]["Visibility"];
            /** Format: date-time */
            createdUtc?: string;
            items?: components["schemas"]["TemplateDto"][];
        };
        BundleDto2: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string | null;
            /** Format: double */
            price?: number;
            currency?: components["schemas"]["Currency"];
            visibility?: components["schemas"]["Visibility"];
            /** Format: date-time */
            createdUtc?: string;
            items?: components["schemas"]["TemplateDto3"][];
        };
        CommentDto: {
            /** Format: uuid */
            id?: string;
            user?: components["schemas"]["AuthorDto"];
            template?: components["schemas"]["TemplateDto2"];
            isForDevelopers?: boolean;
            text?: string;
        };
        CommentDto2: {
            /** Format: uuid */
            id?: string;
            user?: components["schemas"]["AuthorDto"];
            template?: components["schemas"]["TemplateDto4"];
            isForDevelopers?: boolean;
            text?: string;
        };
        CommentDto3: {
            /** Format: uuid */
            id?: string;
            user?: components["schemas"]["AuthorDto"];
            template?: components["schemas"]["TemplateDto6"];
            isForDevelopers?: boolean;
            text?: string;
        };
        CommentDto4: {
            /** Format: uuid */
            id?: string;
            user?: components["schemas"]["AuthorDto"];
            template?: components["schemas"]["TemplateDto8"];
            isForDevelopers?: boolean;
            text?: string;
        };
        CommentDto5: {
            /** Format: uuid */
            id?: string;
            user?: components["schemas"]["AuthorDto"];
            template?: components["schemas"]["TemplateDto10"];
            isForDevelopers?: boolean;
            text?: string;
        };
        Currency: number;
        GetAllPublicBundlesResponse: {
            bundles?: components["schemas"]["BundleDto"][];
        };
        GetAllPublicTemplatesResponse: {
            templates?: components["schemas"]["TemplateDto5"][];
        };
        GetSingleBundleResponse: {
            bundle: components["schemas"]["BundleDto2"];
        };
        GetSingleTemplateResponse: {
            template?: components["schemas"]["TemplateDto7"];
        };
        GetUploadUrlRequest: {
            templateSlug?: string;
            version?: string;
        };
        GetUploadUrlResponse: {
            uploadUrl?: components["schemas"]["UploadUrlDto"];
        };
        GetUserInfoResponse: {
            userInfo: components["schemas"]["UserDto"];
        };
        LicenseKeyDto: {
            /** Format: uuid */
            id?: string;
            key?: string;
            template?: components["schemas"]["TemplateDto10"];
            /** Format: date-time */
            issuedUtc?: string;
            /** Format: date-time */
            revokedUtc?: string | null;
        };
        PostCommentRequest: {
            comment?: string;
            templateId?: string;
            isForDeveloper?: boolean;
        };
        PostTemplateRequest: {
            templateId?: string | null;
            name?: string;
            description?: string;
            slug?: string;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: string;
            version?: string;
            tags?: components["schemas"]["TemplateTag"][];
        };
        PostTemplateResponse: {
            /** Format: uuid */
            id?: string;
        };
        Tag: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        TagDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        TemplateDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: components["schemas"]["Currency"];
            author?: components["schemas"]["AuthorDto"];
            /** Format: uuid */
            currentVersionId?: string | null;
            currentVersion?: components["schemas"]["TemplateVersionDto"];
            /** Format: date-time */
            createdUtc?: string;
            versions?: components["schemas"]["TemplateVersionDto"][];
            tags?: components["schemas"]["TagDto"][];
            comments?: components["schemas"]["CommentDto"][];
        };
        TemplateDto10: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: components["schemas"]["Currency"];
            author?: components["schemas"];
            /** Format: uuid */
            currentVersionId?: string | null;
            currentVersion?: components["schemas"];
            /** Format: date-time */
            createdUtc?: string;
            versions?: components["schemas"];
            tags?: components["schemas"];
            comments?: components["schemas"];
        };
        TemplateDto2: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: components["schemas"]["Currency"];
            author?: components["schemas"];
            /** Format: uuid */
            currentVersionId?: string | null;
            currentVersion?: components["schemas"];
            /** Format: date-time */
            createdUtc?: string;
            versions?: components["schemas"];
            tags?: components["schemas"];
            comments?: components["schemas"];
        };
        TemplateDto3: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: components["schemas"]["Currency"];
            author?: components["schemas"]["AuthorDto"];
            /** Format: uuid */
            currentVersionId?: string | null;
            currentVersion?: components["schemas"]["TemplateVersionDto"];
            /** Format: date-time */
            createdUtc?: string;
            versions?: components["schemas"]["TemplateVersionDto"][];
            tags?: components["schemas"]["TagDto"][];
            comments?: components["schemas"]["CommentDto2"][];
        };
        TemplateDto4: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: components["schemas"]["Currency"];
            author?: components["schemas"];
            /** Format: uuid */
            currentVersionId?: string | null;
            currentVersion?: components["schemas"];
            /** Format: date-time */
            createdUtc?: string;
            versions?: components["schemas"];
            tags?: components["schemas"];
            comments?: components["schemas"];
        };
        TemplateDto5: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: components["schemas"]["Currency"];
            author?: components["schemas"]["AuthorDto"];
            /** Format: uuid */
            currentVersionId?: string | null;
            currentVersion?: components["schemas"]["TemplateVersionDto"];
            /** Format: date-time */
            createdUtc?: string;
            versions?: components["schemas"]["TemplateVersionDto"][];
            tags?: components["schemas"]["TagDto"][];
            comments?: components["schemas"]["CommentDto3"][];
        };
        TemplateDto6: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: components["schemas"]["Currency"];
            author?: components["schemas"];
            /** Format: uuid */
            currentVersionId?: string | null;
            currentVersion?: components["schemas"];
            /** Format: date-time */
            createdUtc?: string;
            versions?: components["schemas"];
            tags?: components["schemas"];
            comments?: components["schemas"];
        };
        TemplateDto7: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: components["schemas"]["Currency"];
            author?: components["schemas"]["AuthorDto"];
            /** Format: uuid */
            currentVersionId?: string | null;
            currentVersion?: components["schemas"]["TemplateVersionDto"];
            /** Format: date-time */
            createdUtc?: string;
            versions?: components["schemas"]["TemplateVersionDto"][];
            tags?: components["schemas"]["TagDto"][];
            comments?: components["schemas"]["CommentDto4"][];
        };
        TemplateDto8: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: components["schemas"]["Currency"];
            author?: components["schemas"];
            /** Format: uuid */
            currentVersionId?: string | null;
            currentVersion?: components["schemas"];
            /** Format: date-time */
            createdUtc?: string;
            versions?: components["schemas"];
            tags?: components["schemas"];
            comments?: components["schemas"];
        };
        TemplateDto9: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            description?: string | null;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: components["schemas"]["Currency"];
            author?: components["schemas"]["AuthorDto"];
            /** Format: uuid */
            currentVersionId?: string | null;
            currentVersion?: components["schemas"]["TemplateVersionDto"];
            /** Format: date-time */
            createdUtc?: string;
            versions?: components["schemas"]["TemplateVersionDto"][];
            tags?: components["schemas"]["TagDto"][];
            comments?: components["schemas"]["CommentDto5"][];
        };
        TemplateTag: {
            /** Format: uuid */
            templateId?: string;
            /** Format: uuid */
            tagId?: string;
            tag?: components["schemas"]["Tag"];
        };
        TemplateVersionDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            templateId?: string;
            semVer?: string;
            changelog?: string | null;
            artifactUrl?: string;
            sha256?: string | null;
            /** Format: date-time */
            publishedUtc?: string;
        };
        UploadUrlDto: {
            /** Format: uri */
            url?: string;
            container?: string;
            name?: string;
            headers?: {
                [key: string]: string;
            };
        };
        UserDto: {
            /** Format: uuid */
            id?: string;
            email?: string;
            displayName?: string;
            /** Format: date-time */
            createdUtc?: string;
            templatesAuthored?: components["schemas"]["TemplateDto9"][];
            licenses?: components["schemas"]["LicenseKeyDto"][];
        };
        Visibility: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
