/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Auth/login/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetAllPublicBundlesResponse"];
                        "application/json": components["schemas"]["GetAllPublicBundlesResponse"];
                        "text/json": components["schemas"]["GetAllPublicBundlesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Bundle/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetSingleBundleResponse"];
                        "application/json": components["schemas"]["GetSingleBundleResponse"];
                        "text/json": components["schemas"]["GetSingleBundleResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetAllPublicTemplatesResponse"];
                        "application/json": components["schemas"]["GetAllPublicTemplatesResponse"];
                        "text/json": components["schemas"]["GetAllPublicTemplatesResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostTemplateRequest"];
                    "text/json": components["schemas"]["PostTemplateRequest"];
                    "application/*+json": components["schemas"]["PostTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PostTemplateResponse"];
                        "application/json": components["schemas"]["PostTemplateResponse"];
                        "text/json": components["schemas"]["PostTemplateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Template/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetSingleTemplateResponse"];
                        "application/json": components["schemas"]["GetSingleTemplateResponse"];
                        "text/json": components["schemas"]["GetSingleTemplateResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Template/version/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostTemplateRequest"];
                    "text/json": components["schemas"]["PostTemplateRequest"];
                    "application/*+json": components["schemas"]["PostTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PostTemplateResponse"];
                        "application/json": components["schemas"]["PostTemplateResponse"];
                        "text/json": components["schemas"]["PostTemplateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Template/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GetUploadUrlRequest"];
                    "text/json": components["schemas"]["GetUploadUrlRequest"];
                    "application/*+json": components["schemas"]["GetUploadUrlRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUploadUrlResponse"];
                        "application/json": components["schemas"]["GetUploadUrlResponse"];
                        "text/json": components["schemas"]["GetUploadUrlResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostCommentRequest"];
                    "text/json": components["schemas"]["PostCommentRequest"];
                    "application/*+json": components["schemas"]["PostCommentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/User/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUserInfoResponse"];
                        "application/json": components["schemas"]["GetUserInfoResponse"];
                        "text/json": components["schemas"]["GetUserInfoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/User/userProfile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetUserInfoResponse"];
                        "application/json": components["schemas"]["GetUserInfoResponse"];
                        "text/json": components["schemas"]["GetUserInfoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Bundle: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            description?: string | null;
            /** Format: int32 */
            price?: number;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string | null;
            bundleTemplates?: components["schemas"][];
            comments?: components["schemas"]["Comment"][];
        };
        Bundle2: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            description?: string | null;
            /** Format: int32 */
            price?: number;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string | null;
            bundleTemplates?: components["schemas"];
            comments?: components["schemas"];
        } | null;
        BundleDto: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            description?: string | null;
            /** Format: int32 */
            price?: number;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            templates?: components["schemas"]["TemplateListItemDto"][];
        };
        BundleTemplate: {
            /** Format: uuid */
            bundleId?: string;
            bundle?: components["schemas"]["Bundle"];
            /** Format: uuid */
            templateId?: string;
            template?: components["schemas"]["Template5"];
            /** Format: int32 */
            sortOrder?: number;
        };
        Comment: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            templateId?: string | null;
            template?: components["schemas"]["Template3"];
            /** Format: uuid */
            bundleId?: string | null;
            bundle?: components["schemas"]["Bundle2"];
            /** Format: uuid */
            userId?: string | null;
            user?: components["schemas"]["User"];
            content: string;
            visibility?: components["schemas"]["Visibility"];
            /** Format: date-time */
            createdAt?: string;
        };
        CommentDto: {
            /** Format: uuid */
            id?: string;
            content: string;
            /** Format: date-time */
            createdAt?: string;
            userDisplayName?: string | null;
            visibility?: components["schemas"]["Visibility"];
        };
        GetAllPublicBundlesResponse: {
            bundles?: components["schemas"]["BundleDto"][];
        };
        GetAllPublicTemplatesResponse: {
            templates?: components["schemas"]["TemplateListItemDto"][];
        };
        GetSingleBundleResponse: {
            bundle: components["schemas"]["BundleDto"];
        };
        GetSingleTemplateResponse: {
            template?: components["schemas"]["TemplateDetailDto"];
        };
        GetUploadUrlRequest: {
            templateSlug?: string;
            version?: string;
        };
        GetUploadUrlResponse: {
            uploadUrl?: components["schemas"]["UploadUrlDto"];
        };
        GetUserInfoResponse: {
            userInfo: components["schemas"]["UserDto"];
        };
        OAuthAccount: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            user?: components["schemas"]["User2"];
            provider: string;
            providerUserId: string;
            userName?: string | null;
            avatarUrl?: string | null;
        };
        Package: {
            /** Format: uuid */
            id?: string;
            name: string;
            version?: string | null;
            packageManager?: components["schemas"]["PackageManager"];
            url?: string | null;
            templatePackages?: components["schemas"][];
        };
        PackageDto: {
            /** Format: uuid */
            id?: string;
            name: string;
            version?: string | null;
            packageManager?: components["schemas"]["PackageManager"];
            url?: string | null;
        };
        PackageManager: number;
        PostCommentRequest: {
            comment?: string;
            itemId?: string;
            visibility?: components["schemas"]["Visibility"];
        };
        PostTemplateRequest: {
            templateId?: string | null;
            name?: string;
            description?: string;
            slug?: string;
            visibility?: components["schemas"]["Visibility"];
            price?: string;
            currency?: string;
            version?: string;
            tags?: components["schemas"]["TemplateTag"][];
        };
        PostTemplateResponse: {
            /** Format: uuid */
            id?: string;
        };
        Tag: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            category?: string | null;
            templateTags?: components["schemas"][];
        };
        TagDto: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            category?: string | null;
        };
        Template: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            shortDescription?: string | null;
            longDescription?: string | null;
            isFree?: boolean;
            /** Format: int32 */
            price?: number;
            authorName?: string;
            demoUrl?: string | null;
            techStackSummary?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string | null;
            templateTags?: components["schemas"][];
            templatePackages?: components["schemas"]["TemplatePackage"][];
            bundleTemplates?: components["schemas"];
            assets?: components["schemas"];
            comments?: components["schemas"];
            versions?: components["schemas"];
        };
        Template2: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            shortDescription?: string | null;
            longDescription?: string | null;
            isFree?: boolean;
            /** Format: int32 */
            price?: number;
            authorName?: string;
            demoUrl?: string | null;
            techStackSummary?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string | null;
            templateTags?: components["schemas"];
            templatePackages?: components["schemas"];
            bundleTemplates?: components["schemas"]["BundleTemplate"][];
            assets?: components["schemas"];
            comments?: components["schemas"];
            versions?: components["schemas"];
        };
        Template3: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            shortDescription?: string | null;
            longDescription?: string | null;
            isFree?: boolean;
            /** Format: int32 */
            price?: number;
            authorName?: string;
            demoUrl?: string | null;
            techStackSummary?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string | null;
            templateTags?: components["schemas"];
            templatePackages?: components["schemas"];
            bundleTemplates?: components["schemas"];
            assets?: components["schemas"]["TemplateAsset"][];
            comments?: components["schemas"];
            versions?: components["schemas"];
        } | null;
        Template4: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            shortDescription?: string | null;
            longDescription?: string | null;
            isFree?: boolean;
            /** Format: int32 */
            price?: number;
            authorName?: string;
            demoUrl?: string | null;
            techStackSummary?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string | null;
            templateTags?: components["schemas"];
            templatePackages?: components["schemas"];
            bundleTemplates?: components["schemas"];
            assets?: components["schemas"];
            comments?: components["schemas"][];
            versions?: components["schemas"]["TemplateVersion"][];
        };
        Template5: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            shortDescription?: string | null;
            longDescription?: string | null;
            isFree?: boolean;
            /** Format: int32 */
            price?: number;
            authorName?: string;
            demoUrl?: string | null;
            techStackSummary?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string | null;
            templateTags?: components["schemas"];
            templatePackages?: components["schemas"];
            bundleTemplates?: components["schemas"];
            assets?: components["schemas"];
            comments?: components["schemas"];
            versions?: components["schemas"];
        };
        Template6: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            shortDescription?: string | null;
            longDescription?: string | null;
            isFree?: boolean;
            /** Format: int32 */
            price?: number;
            authorName?: string;
            demoUrl?: string | null;
            techStackSummary?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string | null;
            templateTags?: components["schemas"];
            templatePackages?: components["schemas"];
            bundleTemplates?: components["schemas"];
            assets?: components["schemas"];
            comments?: components["schemas"];
            versions?: components["schemas"];
        } | null;
        TemplateAsset: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            templateId?: string;
            template?: components["schemas"]["Template4"];
            type?: components["schemas"]["TemplateAssetType"];
            blobContainer: string;
            blobName: string;
            fileName?: string | null;
            contentType?: string | null;
            /** Format: int64 */
            sizeBytes?: number | null;
            /** Format: date-time */
            createdAt?: string;
            isActive?: boolean;
        };
        TemplateAsset2: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            templateId?: string;
            template?: components["schemas"];
            type?: components["schemas"]["TemplateAssetType"];
            blobContainer: string;
            blobName: string;
            fileName?: string | null;
            contentType?: string | null;
            /** Format: int64 */
            sizeBytes?: number | null;
            /** Format: date-time */
            createdAt?: string;
            isActive?: boolean;
        } | null;
        TemplateAssetType: number;
        TemplateDetailDto: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            shortDescription?: string | null;
            longDescription?: string | null;
            isFree?: boolean;
            /** Format: int32 */
            price?: number;
            authorName?: string;
            techStackSummary?: string | null;
            /** Format: date-time */
            createdAt?: string;
            tags?: components["schemas"]["TagDto"][];
            packages?: components["schemas"]["PackageDto"][];
            mainDownloadUrl?: string | null;
            thumbnailUrl?: string | null;
            comments?: components["schemas"]["CommentDto"][];
            templateVersions?: components["schemas"]["TemplateVersionDto"][];
        };
        TemplateListItemDto: {
            /** Format: uuid */
            id?: string;
            name: string;
            slug: string;
            shortDescription?: string | null;
            isFree?: boolean;
            /** Format: int32 */
            price?: number;
            techStackSummary?: string | null;
            /** Format: date-time */
            createdAt?: string;
            tags?: components["schemas"]["TagDto"][];
            thumbnailUrl?: string | null;
        };
        TemplatePackage: {
            /** Format: uuid */
            templateId?: string;
            template?: components["schemas"]["Template2"];
            /** Format: uuid */
            packageId?: string;
            package?: components["schemas"]["Package"];
            notes?: string | null;
        };
        TemplateTag: {
            /** Format: uuid */
            templateId?: string;
            template?: components["schemas"]["Template"];
            /** Format: uuid */
            tagId?: string;
            tag?: components["schemas"]["Tag"];
        };
        TemplateVersion: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            templateId?: string;
            template?: components["schemas"]["Template5"];
            version: string;
            notes?: string | null;
            /** Format: uuid */
            assetId?: string | null;
            asset?: components["schemas"]["TemplateAsset2"];
            /** Format: date-time */
            createdAt?: string;
            isDeprecated?: boolean;
            isLatest?: boolean;
        };
        TemplateVersionDto: {
            /** Format: uuid */
            id?: string;
            version: string;
            notes?: string | null;
            /** Format: date-time */
            createdAt?: string;
            isDeprecated?: boolean;
            isLatest?: boolean;
        };
        UploadUrlDto: {
            /** Format: uri */
            url?: string;
            container?: string;
            name?: string;
            headers?: {
                [key: string]: string;
            };
        };
        User: {
            /** Format: uuid */
            id?: string;
            email: string;
            displayName: string;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
            oAuthAccounts?: components["schemas"]["OAuthAccount"][];
            purchases?: components["schemas"];
            favorites?: components["schemas"];
        } | null;
        User2: {
            /** Format: uuid */
            id?: string;
            email: string;
            displayName: string;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
            oAuthAccounts?: components["schemas"];
            purchases?: components["schemas"]["UserPurchase"][];
            favorites?: components["schemas"];
        };
        User3: {
            /** Format: uuid */
            id?: string;
            email: string;
            displayName: string;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
            oAuthAccounts?: components["schemas"];
            purchases?: components["schemas"];
            favorites?: components["schemas"]["UserFavorite"][];
        };
        User4: {
            /** Format: uuid */
            id?: string;
            email: string;
            displayName: string;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
            oAuthAccounts?: components["schemas"];
            purchases?: components["schemas"];
            favorites?: components["schemas"];
        };
        UserDto: {
            /** Format: uuid */
            id?: string;
            email: string;
            displayName: string;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        UserFavorite: {
            /** Format: uuid */
            userId?: string;
            user?: components["schemas"]["User4"];
            /** Format: uuid */
            templateId?: string;
            template?: components["schemas"]["Template5"];
            /** Format: date-time */
            addedAt?: string;
        };
        UserPurchase: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            user?: components["schemas"]["User3"];
            /** Format: uuid */
            templateId?: string | null;
            template?: components["schemas"]["Template6"];
            /** Format: uuid */
            bundleId?: string | null;
            bundle?: components["schemas"]["Bundle2"];
            /** Format: date-time */
            purchasedAt?: string;
            paymentId?: string | null;
        };
        Visibility: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
